test("mon premier test" , () => {})
// npm test 
test("mon deuxiÃ¨me test", () => {
    throw new Erreur("une erreur s'est produite");
})
// npm test